/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ride {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'distanceKm' : number,
  'durationMinutes' : bigint,
  'notes' : string,
  'rating' : bigint,
}
export interface RideStats {
  'avgDistanceKm' : number,
  'longestRideName' : string,
  'totalDistanceKm' : number,
  'totalDurationMinutes' : bigint,
  'totalRides' : bigint,
  'longestRideKm' : number,
}
export interface _SERVICE {
  'createRide' : ActorMethod<
    [string, string, number, bigint, string, bigint],
    Ride
  >,
  'deleteRide' : ActorMethod<[bigint], undefined>,
  'getAllRides' : ActorMethod<[], Array<Ride>>,
  'getRide' : ActorMethod<[bigint], Ride>,
  'getStats' : ActorMethod<[], RideStats>,
  'updateRide' : ActorMethod<
    [bigint, string, string, number, bigint, string, bigint],
    Ride
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];