/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Ride = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'rating' : IDL.Nat,
});
export const RideStats = IDL.Record({
  'avgDistanceKm' : IDL.Float64,
  'longestRideName' : IDL.Text,
  'totalDistanceKm' : IDL.Float64,
  'totalDurationMinutes' : IDL.Nat,
  'totalRides' : IDL.Nat,
  'longestRideKm' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createRide' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
      [Ride],
      [],
    ),
  'deleteRide' : IDL.Func([IDL.Nat], [], []),
  'getAllRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getRide' : IDL.Func([IDL.Nat], [Ride], ['query']),
  'getStats' : IDL.Func([], [RideStats], ['query']),
  'updateRide' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
      [Ride],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Ride = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const RideStats = IDL.Record({
    'avgDistanceKm' : IDL.Float64,
    'longestRideName' : IDL.Text,
    'totalDistanceKm' : IDL.Float64,
    'totalDurationMinutes' : IDL.Nat,
    'totalRides' : IDL.Nat,
    'longestRideKm' : IDL.Float64,
  });
  
  return IDL.Service({
    'createRide' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
        [Ride],
        [],
      ),
    'deleteRide' : IDL.Func([IDL.Nat], [], []),
    'getAllRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getRide' : IDL.Func([IDL.Nat], [Ride], ['query']),
    'getStats' : IDL.Func([], [RideStats], ['query']),
    'updateRide' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
        [Ride],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };